/**
 * AI Platform shared constants — Redis key prefixes, TTLs, defaults.
 */

export const AI_PLATFORM_CONSTANTS = {
  FEATURE_NAME: 'AI_PLATFORM',

  /** Redis namespace (Phase 1+ migration from tutor: keys) */
  KEY_PREFIX_EMBED: 'ai:embed:',
  KEY_PREFIX_SESSION: 'ai:session:',
  KEY_PREFIX_RATE: 'ai:rate:',
  KEY_PREFIX_ACTIVE_STREAMS: 'ai:active-streams:',
  KEY_PREFIX_DAILY_COST: 'ai:daily-cost:',
  KEY_PREFIX_CONVERSATION: 'ai:conversation:',

  SESSION_CACHE_TTL_MS: 5 * 60 * 1000,

  EMBEDDING_DIMENSIONS: 1536,
  EMBEDDING_BATCH_SIZE: 25,
  EMBEDDING_CACHE_TTL_SECONDS: 3600,

  COURSE_INDEXING_QUEUE: 'course-indexing',
  COURSE_INDEXING_BOOTSTRAP_LOCK_KEY: 'course-indexing:bootstrap:lock',
  COURSE_INDEXING_BOOTSTRAP_LOCK_TTL_SECONDS: 300,
  COURSE_INDEXING_WORKER_HEARTBEAT_KEY: 'ai:worker:course-indexing:heartbeat',

  AI_COST_AGGREGATION_QUEUE: 'ai-cost-aggregation',
  AI_EVALUATION_QUEUE: 'ai-evaluation',

  DEFAULT_TOP_K: 10,
  DEFAULT_MIN_SIMILARITY: 0.7,
  DEFAULT_LECTURE_FALLBACK_MIN_SIMILARITY: 0.3,

  REQUEST_TIMEOUT_MS: 60_000,
  MAX_RESPONSE_TOKENS: 402,
  MAX_PROMPT_TOKENS: 8000,
  MAX_CONCURRENT_STREAMS_PER_USER: 2,

  MAX_MESSAGE_LENGTH: 5000,

  CONVERSATION_MEMORY_TURN_LIMIT: 20,
  CONVERSATION_MEMORY_TTL_SECONDS: 60 * 60 * 24,

  RATE_LIMIT_REQUESTS_PER_MINUTE: 30,
  RATE_LIMIT_REQUESTS_PER_HOUR: 300,
  RATE_LIMIT_REQUESTS_PER_DAY: 1000,

  INDEXING_CHUNK_MAX_CHARS: 1000,
  INDEXING_CHUNK_MIN_CHARS: 100,
  INDEXING_CHUNK_OVERLAP_CHARS: 100,
  INDEXING_MAX_TOKENS_PER_CHUNK: 500,
  INDEXING_MAX_TRANSCRIPT_CHARS: 500_000,
  KNOWLEDGE_INGESTION_SOURCE_CONCURRENCY: 3,
} as const;
